collections:
  codes:
    output: true

kramdown:
  syntax_highlighter_opts:
    disable : false

defaults:
  - scope:
      path: ""
      type: "codes"
    values:
      layout: "code"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "codes"
      type: "OtherWorks"
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag